server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # change to 'validate' after stable
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  data:
    jpa:
      repositories:
        bootstrap-mode: default

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000

logging:
  level:
    com.apexglobal.erp: INFO
    org.springframework.security: WARN
